/** @format */

export const initstate = {
	profiles: [
		{
			SNO: "1",
			AdmissionNumber: "SAV-10-01",
			StudentName: "SHUBHAM SUDHANSHU",
			FathersName: "UMESH KUMAR",
		},
		{
			SNO: "2",
			AdmissionNumber: "SAV-10-02",
			StudentName: "VINAY KUMAR",
			FathersName: "LATE DILIP PASWAN",
		},
		{
			SNO: "3",
			AdmissionNumber: "SAV-10-03",
			StudentName: "ANKIT KUMAR",
			FathersName: "AJAY KUMAR CHOUDHARY",
		},
		{
			SNO: "4",
			AdmissionNumber: "SAV-10-04",
			StudentName: "BIMAL ANAND",
			FathersName: "AKHILESH KUMAR SINGH",
		},
		{
			SNO: "5",
			AdmissionNumber: "SAV-10-05",
			StudentName: "AMAN KUMAR",
			FathersName: "MANOJ SHARMA",
		},
		{
			SNO: "6",
			AdmissionNumber: "SAV-10-06",
			StudentName: "AMAN KUMAR RAY",
			FathersName: "UCHIT RAY",
		},
		{
			SNO: "7",
			AdmissionNumber: "SAV-10-07",
			StudentName: "NISHANT KUMAR",
			FathersName: "RAVINDRA PRASAD RAI",
		},
		{
			SNO: "8",
			AdmissionNumber: "SAV-10-08",
			StudentName: "VAIBHAV PRATAP",
			FathersName: "TEJ PRATAP SINGH",
		},
		{
			SNO: "9",
			AdmissionNumber: "SAV-10-09",
			StudentName: "GAURAV BAGHEL",
			FathersName: "HIMANSHU SHEKHAR BAGHEL",
		},
		{
			SNO: "10",
			AdmissionNumber: "SAV-10-10",
			StudentName: "AMAN KUMAR",
			FathersName: "VIJENDRA KUMAR",
		},
		{
			SNO: "11",
			AdmissionNumber: "SAV-10-11",
			StudentName: "CHAMAN RAJ",
			FathersName: "RAVI NANDAN SINGH",
		},
		{
			SNO: "12",
			AdmissionNumber: "SAV-10-12",
			StudentName: "KAMLESH KUMAR",
			FathersName: "KRISHNA KUMAR SINGH",
		},
		{
			SNO: "13",
			AdmissionNumber: "SAV-10-13",
			StudentName: "ANURAG ANKIT",
			FathersName: "DINESH SINGH",
		},
		{
			SNO: "14",
			AdmissionNumber: "SAV-10-14",
			StudentName: "AMAN BHARDWAJ",
			FathersName: "RAGHWENDRA KUMAR",
		},
		{
			SNO: "15",
			AdmissionNumber: "SAV-10-16",
			StudentName: "VIVEK VAIBHAW",
			FathersName: "MANOJ PANDEY",
		},
		{
			SNO: "16",
			AdmissionNumber: "SAV-10-17",
			StudentName: "SAKIB SHAUKAT",
			FathersName: "SHAUKAT ALI",
		},
		{
			SNO: "17",
			AdmissionNumber: "SAV-10-18",
			StudentName: "SANNI KUMAR",
			FathersName: "NILKAMAL MISHRA",
		},
		{
			SNO: "18",
			AdmissionNumber: "SAV-10-19",
			StudentName: "ABHINAV ADARSH",
			FathersName: "ANAND KUMAR",
		},
		{
			SNO: "19",
			AdmissionNumber: "SAV-10-20",
			StudentName: "VIKASH KUMAR",
			FathersName: "DAYANAND KUMAR",
		},
		{
			SNO: "20",
			AdmissionNumber: "SAV-10-21",
			StudentName: "SHIV PRAKASH",
			FathersName: "RAM SHOBHIT SAH",
		},
		{
			SNO: "21",
			AdmissionNumber: "SAV-10-22",
			StudentName: "CHITRANJAN KUMAR",
			FathersName: "KEDAR SAH",
		},
		{
			SNO: "22",
			AdmissionNumber: "SAV-10-23",
			StudentName: "SAURABH KUMAR",
			FathersName: "NAGENDRA SINGH",
		},
		{
			SNO: "23",
			AdmissionNumber: "SAV-10-24",
			StudentName: "GAURAV RAJ",
			FathersName: "MANOJ RAM",
		},
		{
			SNO: "24",
			AdmissionNumber: "SAV-10-25",
			StudentName: "MD. TANVEER ANSARI",
			FathersName: "MD. ARULESH ANSARI",
		},
		{
			SNO: "25",
			AdmissionNumber: "SAV-10-26",
			StudentName: "BANTI KUMAR",
			FathersName: "AMIT KUMAR",
		},
		{
			SNO: "26",
			AdmissionNumber: "SAV-10-27",
			StudentName: "JAYANT KUMAR",
			FathersName: "AJAY KUMAR SINGH",
		},
		{
			SNO: "27",
			AdmissionNumber: "SAV-10-28",
			StudentName: "VIVEK KUMAR",
			FathersName: "RAM NARESH SINGH",
		},
		{
			SNO: "28",
			AdmissionNumber: "SAV-10-29",
			StudentName: "SANGAM KUMAR",
			FathersName: "HARI NANDAN YADAV",
		},
		{
			SNO: "29",
			AdmissionNumber: "SAV-10-30",
			StudentName: "MANVENDRA KRISHNA",
			FathersName: "TEJ NARAYAN SINGH",
		},
		{
			SNO: "30",
			AdmissionNumber: "SAV-10-31",
			StudentName: "SHIVAM RAJ",
			FathersName: "PANKAJ SINGH",
		},
		{
			SNO: "31",
			AdmissionNumber: "SAV-10-32",
			StudentName: "ARVIND KUMAR",
			FathersName: "UMESH CHAUDHARY",
		},
		{
			SNO: "32",
			AdmissionNumber: "SAV-10-33",
			StudentName: "SANTOSH KUMAR",
			FathersName: "BIJAY KUMAR",
		},
		{
			SNO: "33",
			AdmissionNumber: "SAV-10-34",
			StudentName: "MD. AQIB JAVED",
			FathersName: "MD. HABIB ALAM",
		},
		{
			SNO: "34",
			AdmissionNumber: "SAV-10-35",
			StudentName: "KUNDAN KUMAR",
			FathersName: "KRISHNANAND THAKUR",
		},
		{
			SNO: "35",
			AdmissionNumber: "SAV-10-36",
			StudentName: "DHIRAJ KUMAR",
			FathersName: "HIRALAL SINGH",
		},
		{
			SNO: "36",
			AdmissionNumber: "SAV-10-37",
			StudentName: "SAURABH KUMAR",
			FathersName: "RAM EKBAL PANDEY",
		},
		{
			SNO: "37",
			AdmissionNumber: "SAV-10-38",
			StudentName: "ANKIT ABHISHEK",
			FathersName: "DEVENDRA CHOUDHARY",
		},
		{
			SNO: "38",
			AdmissionNumber: "SAV-10-39",
			StudentName: "SUMIT MANDAL",
			FathersName: "PRAKASH MANDAL",
		},
		{
			SNO: "39",
			AdmissionNumber: "SAV-10-40",
			StudentName: "SHUBHAM RAJ",
			FathersName: "SARVESH KUMAR SINGH",
		},
		{
			SNO: "40",
			AdmissionNumber: "SAV-10-41",
			StudentName: "ABHINAV KUMAR",
			FathersName: "SAMBHU SARAN CAUHAN",
		},
		{
			SNO: "41",
			AdmissionNumber: "SAV-10-42",
			StudentName: "SURAJ KUMAR",
			FathersName: "RAKESH KUMAR THAKUR",
		},
		{
			SNO: "42",
			AdmissionNumber: "SAV-10-43",
			StudentName: "NIRAJ KUMAR",
			FathersName: "RAJENDRA RAVIDAS",
		},
		{
			SNO: "43",
			AdmissionNumber: "SAV-10-44",
			StudentName: "KUMAR ARYABHATTA",
			FathersName: "INDRADEV PRASAD YADAV",
		},
		{
			SNO: "44",
			AdmissionNumber: "SAV-10-45",
			StudentName: "NIRAJ RANJAN",
			FathersName: "MITHILESH KUMAR",
		},
		{
			SNO: "45",
			AdmissionNumber: "SAV-10-46",
			StudentName: "SAKET KUMAR",
			FathersName: "DEV KUMAR SINGH",
		},
		{
			SNO: "46",
			AdmissionNumber: "SAV-10-47",
			StudentName: "AVINAL KUMAR",
			FathersName: "ANIL CHOUDHARY",
		},
		{
			SNO: "47",
			AdmissionNumber: "SAV-10-48",
			StudentName: "KUNAL JIGYASU",
			FathersName: "ASHOK KUMAR MANDAL",
		},
		{
			SNO: "48",
			AdmissionNumber: "SAV-10-50",
			StudentName: "PRAMOD KUMAR TUDU",
			FathersName: "BIJENDRA TUDU",
		},
		{
			SNO: "49",
			AdmissionNumber: "SAV-10-51",
			StudentName: "HIMANSU SAGAR",
			FathersName: "SUNIL KUMAR",
		},
		{
			SNO: "50",
			AdmissionNumber: "SAV-10-52",
			StudentName: "ROHIT KUMAR",
			FathersName: "SATISH PRASAD",
		},
		{
			SNO: "51",
			AdmissionNumber: "SAV-10-53",
			StudentName: "ABHISHEK KUMAR",
			FathersName: "ARVIND SINGH",
		},
		{
			SNO: "52",
			AdmissionNumber: "SAV-10-54",
			StudentName: "MUKUL RANJAN",
			FathersName: "SIARAM PRASAD",
		},
		{
			SNO: "53",
			AdmissionNumber: "SAV-10-55",
			StudentName: "SONU KUMAR",
			FathersName: "PARMESHWAR SHARMA",
		},
		{
			SNO: "54",
			AdmissionNumber: "SAV-10-56",
			StudentName: "SANJAY KUMAR DIVAKAR",
			FathersName: "BHOLA RAJAK",
		},
		{
			SNO: "55",
			AdmissionNumber: "SAV-10-57",
			StudentName: "MD. ASHFAQUE KHALID",
			FathersName: "MD. SAKIL ANSARI",
		},
		{
			SNO: "56",
			AdmissionNumber: "SAV-10-61",
			StudentName: "AJNIKA KUMARI",
			FathersName: "BIJENDRA PRASAD",
		},
		{
			SNO: "57",
			AdmissionNumber: "SAV-10-62",
			StudentName: "SHALINI SAURAV",
			FathersName: "SUNIL PRASAD SAHA",
		},
		{
			SNO: "58",
			AdmissionNumber: "SAV-10-63",
			StudentName: "RAJ LAXMI",
			FathersName: "SUDESH KUMAR",
		},
		{
			SNO: "59",
			AdmissionNumber: "SAV-10-64",
			StudentName: "AKRITI RANJAN",
			FathersName: "ANUJ KUMAR NIRALA",
		},
		{
			SNO: "60",
			AdmissionNumber: "SAV-10-65",
			StudentName: "ANAMIKA BHARTI",
			FathersName: "RAM KUMAR",
		},
		{
			SNO: "61",
			AdmissionNumber: "SAV-10-66",
			StudentName: "DEEPSHIKHA KUMARI",
			FathersName: "MRITUNJAY LAL DAS",
		},
		{
			SNO: "62",
			AdmissionNumber: "SAV-10-67",
			StudentName: "KASHISH",
			FathersName: "KISHOR KUMAR",
		},
		{
			SNO: "63",
			AdmissionNumber: "SAV-10-68",
			StudentName: "ANSHU PRIYA",
			FathersName: "BHOLA NATH PATHAK",
		},
		{
			SNO: "64",
			AdmissionNumber: "SAV-10-69",
			StudentName: "RICHA RANJAN",
			FathersName: "HEMANT KUMAR",
		},
		{
			SNO: "65",
			AdmissionNumber: "SAV-10-70",
			StudentName: "JYOTI KUMARI",
			FathersName: "LAL SURAJ RAM",
		},
		{
			SNO: "66",
			AdmissionNumber: "SAV-10-71",
			StudentName: "PALLAVI GUDAN",
			FathersName: "TEJ NARAYANA SINGH",
		},
		{
			SNO: "67",
			AdmissionNumber: "SAV-10-72",
			StudentName: "NUTAN KUMARI",
			FathersName: "SUNIL KUMAR",
		},
		{
			SNO: "68",
			AdmissionNumber: "SAV-10-73",
			StudentName: "SANJANA KUMARI",
			FathersName: "GANESH PRASAD GUPTA",
		},
		{
			SNO: "69",
			AdmissionNumber: "SAV-10-74",
			StudentName: "PRACHI PRIYA",
			FathersName: "AVINASH CHOUDHARY",
		},
		{
			SNO: "70",
			AdmissionNumber: "SAV-10-75",
			StudentName: "ASTHA JYOTI",
			FathersName: "BIPIN KUMAR",
		},
		{
			SNO: "71",
			AdmissionNumber: "SAV-10-78",
			StudentName: "SURABHI RAMAN",
			FathersName: "RAMAN KUMAR SRIVASTAVA",
		},
		{
			SNO: "72",
			AdmissionNumber: "SAV-10-79",
			StudentName: "SIDDHIDATRI KUMARI",
			FathersName: "NAND KISHOR KAJI",
		},
		{
			SNO: "73",
			AdmissionNumber: "SAV-10-80",
			StudentName: "SHREYA SHREE",
			FathersName: "RAMANAND PANDIT",
		},
		{
			SNO: "74",
			AdmissionNumber: "SAV-10-81",
			StudentName: "PUJA KUMARI",
			FathersName: "NIRANJAN MANDAL",
		},
		{
			SNO: "75",
			AdmissionNumber: "SAV-10-82",
			StudentName: "SHRUTI KUMARI",
			FathersName: "JAY PRAKASH GUPTA",
		},
		{
			SNO: "76",
			AdmissionNumber: "SAV-10-83",
			StudentName: "SONI SUPRIYA",
			FathersName: "HARI KISHOR THAKUR",
		},
		{
			SNO: "77",
			AdmissionNumber: "SAV-10-84",
			StudentName: "LAXMI KUMARI",
			FathersName: "BARUN KUMAR",
		},
		{
			SNO: "78",
			AdmissionNumber: "SAV-10-85",
			StudentName: "PUJA KUMARI",
			FathersName: "KAILASH PRASAD",
		},
		{
			SNO: "79",
			AdmissionNumber: "SAV-10-86",
			StudentName: "VINAMRATA RANI",
			FathersName: "RAVIKANT SINGH",
		},
		{
			SNO: "80",
			AdmissionNumber: "SAV-10-87",
			StudentName: "PRATIBHA KUMARI",
			FathersName: "BIHARI LAL PANJIYARA",
		},
		{
			SNO: "81",
			AdmissionNumber: "SAV-10-88",
			StudentName: "ARCHANA RANJAN",
			FathersName: "RAJIV KUMAR RANJAN",
		},
		{
			SNO: "82",
			AdmissionNumber: "SAV-10-89",
			StudentName: "SAMRIN FATMA",
			FathersName: "MD. IMTIYAZ ALAM",
		},
		{
			SNO: "83",
			AdmissionNumber: "SAV-10-90",
			StudentName: "PRIYA PRATIK",
			FathersName: "AJAY KUMAR YADAV",
		},
		{
			SNO: "84",
			AdmissionNumber: "SAV-10-91",
			StudentName: "ASTHA RAI",
			FathersName: "SURENDRA PRASAD",
		},
		{
			SNO: "85",
			AdmissionNumber: "SAV-10-92",
			StudentName: "SWETA RAJ",
			FathersName: "DINANATH RAJAK",
		},
		{
			SNO: "86",
			AdmissionNumber: "SAV-10-93",
			StudentName: "DIVYA RANI",
			FathersName: "RANJEET KUMAR",
		},
		{
			SNO: "87",
			AdmissionNumber: "SAV-10-94",
			StudentName: "TEJASWI KUMARI",
			FathersName: "SATYAPAL KUMAR",
		},
		{
			SNO: "88",
			AdmissionNumber: "SAV-10-95",
			StudentName: "SUSHMITA",
			FathersName: "JAINENDRA KUMAR NIRALA",
		},
		{
			SNO: "89",
			AdmissionNumber: "SAV-10-96",
			StudentName: "MUSKAN KUMARI",
			FathersName: "GOVIND PRASAD SAH",
		},
		{
			SNO: "90",
			AdmissionNumber: "SAV-10-97",
			StudentName: "SWARNAM SINHA",
			FathersName: "VINAY KUMAR",
		},
		{
			SNO: "91",
			AdmissionNumber: "SAV-10-98",
			StudentName: "HIMADRI PATEL",
			FathersName: "BIRENDRA KUMAR PATEL",
		},
		{
			SNO: "92",
			AdmissionNumber: "SAV-10-99",
			StudentName: "RIYA RAJ",
			FathersName: "DYANAND KUMAR",
		},
		{
			SNO: "93",
			AdmissionNumber: "SAV-10-100",
			StudentName: "SHILPI KUMARI",
			FathersName: "PRADEEP SAH",
		},
		{
			SNO: "94",
			AdmissionNumber: "SAV-10-101",
			StudentName: "RINA KUMARI",
			FathersName: "KAILASH RAJAK",
		},
		{
			SNO: "95",
			AdmissionNumber: "SAV-10-102",
			StudentName: "PUJA KUMARI",
			FathersName: "UDAY PRASAD",
		},
		{
			SNO: "96",
			AdmissionNumber: "SAV-10-103",
			StudentName: "APARNA RAJ",
			FathersName: "JETA KUMAR",
		},
		{
			SNO: "97",
			AdmissionNumber: "SAV-10-105",
			StudentName: "ADITI SHREE",
			FathersName: "KRISHNA KUMAR PRASAD",
		},
		{
			SNO: "98",
			AdmissionNumber: "SAV-10-106",
			StudentName: "PUJA KUMARI",
			FathersName: "DUKH HARAN PRASAD SINGH",
		},
		{
			SNO: "99",
			AdmissionNumber: "SAV-10-107",
			StudentName: "VANDANA KUMARI",
			FathersName: "BHARAT KUMAR SADAIV",
		},
		{
			SNO: "100",
			AdmissionNumber: "SAV-10-108",
			StudentName: "KHUSHBU KUMARI",
			FathersName: "ABHAY KUMAR",
		},
		{
			SNO: "101",
			AdmissionNumber: "SAV-10-109",
			StudentName: "SMRITI KUMARI",
			FathersName: "SANJAY PRASAD",
		},
		{
			SNO: "102",
			AdmissionNumber: "SAV-10-110",
			StudentName: "PRITI KUMARI",
			FathersName: "ABHAY KUMAR",
		},
		{
			SNO: "103",
			AdmissionNumber: "SAV-10-112",
			StudentName: "VANDANA RAJ",
			FathersName: "OM PRAKASH KUMAR",
		},
		{
			SNO: "104",
			AdmissionNumber: "SAV-10-113",
			StudentName: "SURBHI CHAUHAN",
			FathersName: "ASHOK PRYADARSHI",
		},
		{
			SNO: "105",
			AdmissionNumber: "SAV-10-114",
			StudentName: "RITU RASHMI",
			FathersName: "RAVINDRA KUMAR SINGH",
		},
		{
			SNO: "106",
			AdmissionNumber: "SAV-10-115",
			StudentName: "MADHU KUMARI",
			FathersName: "PREM CHAND CHOURASIA",
		},
		{
			SNO: "107",
			AdmissionNumber: "SAV-10-116",
			StudentName: "PREETI KUMARI",
			FathersName: "MANOJ KUMAR",
		},
		{
			SNO: "108",
			AdmissionNumber: "SAV-10-117",
			StudentName: "SHALINI KUMARI",
			FathersName: "",
		},
	],
};
