/** @format */

export const initstate13 = {
	profiles: [
		{
			SNO: "1",
			AdmissionNumber: "SAV-13-01",
			StudentName: "KAUSHAL KUMAR",
			MotherName: "SARITA DEVI",
			FathersName: "ARUN PRASAD SAH",
		},
		{
			SNO: "2",
			AdmissionNumber: "SAV-13-02",
			StudentName: "AASHISH KUMAR",
			MotherName: "SNEH LATA DEVI",
			FathersName: "SHRIKANT KUMAR",
		},
		{
			SNO: "3",
			AdmissionNumber: "SAV-13-03",
			StudentName: "KUNDAN KUMAR",
			MotherName: "DEWANTI KUMARI",
			FathersName: "PANKAJ KUMAR SINHA",
		},
		{
			SNO: "4",
			AdmissionNumber: "SAV-13-04",
			StudentName: "AKASH KUMAR",
			MotherName: "SIMA DEVI",
			FathersName: "ARVIND KUMAR SINGH",
		},
		{
			SNO: "5",
			AdmissionNumber: "SAV-13-05",
			StudentName: "VAIBHAV RANJAN",
			MotherName: "KUMARI BOBBY SINHA",
			FathersName: "RAJIV RANJAN KUMAR",
		},
		{
			SNO: "6",
			AdmissionNumber: "SAV-13-06",
			StudentName: "AMIT KUMAR",
			MotherName: "USHA DEVI",
			FathersName: "RAMJEE PRASAD",
		},
		{
			SNO: "7",
			AdmissionNumber: "SAV-13-07",
			StudentName: "RAUNAK RAJ",
			MotherName: "SHOBHA DEVI",
			FathersName: "AMIT KUMAR",
		},
		{
			SNO: "8",
			AdmissionNumber: "SAV-13-08",
			StudentName: "AMAN KUMAR",
			MotherName: "SANJU KUMARI",
			FathersName: "ABIRENDRA KUMAR",
		},
		{
			SNO: "9",
			AdmissionNumber: "SAV-13-09",
			StudentName: "ABHISHEK KUMAR",
			MotherName: "GANITA DEVI",
			FathersName: "PARMESHWAR SHARMA",
		},
		{
			SNO: "10",
			AdmissionNumber: "SAV-13-10",
			StudentName: "AKHILESH KUMAR",
			MotherName: "RITA DEVI",
			FathersName: "RAMJEET SINGH",
		},
		{
			SNO: "11",
			AdmissionNumber: "SAV-13-11",
			StudentName: "SAMEER KUMAR",
			MotherName: "USHA DEVI",
			FathersName: "LATE BIRENDRA SINGH",
		},
		{
			SNO: "12",
			AdmissionNumber: "SAV-13-12",
			StudentName: "SAMEER RAJ",
			MotherName: "ASHA GUPTA",
			FathersName: "LATE BHARAT PRASAD GUPTA",
		},
		{
			SNO: "13",
			AdmissionNumber: "SAV-13-13",
			StudentName: "SUBODH KUMAR",
			MotherName: "RAMAWATI DEVI",
			FathersName: "ASHOK SINGH",
		},
		{
			SNO: "14",
			AdmissionNumber: "SAV-13-14",
			StudentName: "SANJIT KUMAR",
			MotherName: "RITA DEVI",
			FathersName: "RAMAYAN SINGH",
		},
		{
			SNO: "15",
			AdmissionNumber: "SAV-13-15",
			StudentName: "SHUBHAM KUMAR",
			MotherName: "USHA KUMARI",
			FathersName: "SUNIL KUMAR",
		},
		{
			SNO: "16",
			AdmissionNumber: "SAV-13-16",
			StudentName: "KISHAN KUMAR",
			MotherName: "VINEETA DEVI",
			FathersName: "RAM SINHASAN YADAV",
		},
		{
			SNO: "17",
			AdmissionNumber: "SAV-13-17",
			StudentName: "AMIT ANAND",
			MotherName: "RITA KUMARI",
			FathersName: "ANIL KUMAR SINGH",
		},
		{
			SNO: "18",
			AdmissionNumber: "SAV-13-18",
			StudentName: "SANDEEP KUMAR",
			MotherName: "BASMATO DEVI",
			FathersName: "CHHEDI SINGH",
		},
		{
			SNO: "19",
			AdmissionNumber: "SAV-13-19",
			StudentName: "KUNDAN KUMAR",
			MotherName: "REKHA DEVI",
			FathersName: "MAHENDRA SAH",
		},
		{
			SNO: "20",
			AdmissionNumber: "SAV-13-20",
			StudentName: "PHULE KANT RANJAN",
			MotherName: "LAKHPATI DEVI",
			FathersName: "SANTOSH KUMAR",
		},
		{
			SNO: "21",
			AdmissionNumber: "SAV-13-21",
			StudentName: "DAYASAGAR",
			MotherName: "SUPRIYA DEVI",
			FathersName: "DHARMENDRA SINGH",
		},
		{
			SNO: "22",
			AdmissionNumber: "SAV-13-22",
			StudentName: "ANURAG THAKUR",
			MotherName: "AMRAVATI DEVI",
			FathersName: "SUDHAKAR THAKUR",
		},
		{
			SNO: "23",
			AdmissionNumber: "SAV-13-23",
			StudentName: "AJAY KUMAR",
			MotherName: "SANGITA DEVI",
			FathersName: "RAMLAL RAM",
		},
		{
			SNO: "24",
			AdmissionNumber: "SAV-13-24",
			StudentName: "ROHIT KUMAR",
			MotherName: "RUKMINI DEVI",
			FathersName: "GANGA SAGAR SINGH",
		},
		{
			SNO: "25",
			AdmissionNumber: "SAV-13-25",
			StudentName: "SUMIT KUMAR",
			MotherName: "ANJU DEVI",
			FathersName: "HARENDRA PRASAD",
		},
		{
			SNO: "26",
			AdmissionNumber: "SAV-13-26",
			StudentName: "ANKIT KUMAR",
			MotherName: "RUBI DEVI",
			FathersName: "AJAY SHAW",
		},
		{
			SNO: "27",
			AdmissionNumber: "SAV-13-27",
			StudentName: "AVDESH KUMAR",
			MotherName: "LT. TRIPHOOL DEVI",
			FathersName: "NANDU YADAV",
		},
		{
			SNO: "28",
			AdmissionNumber: "SAV-13-28",
			StudentName: "EJAZ AHMAD",
			MotherName: "REHANA BEGUM",
			FathersName: "IMAMUL HAQU",
		},
		{
			SNO: "29",
			AdmissionNumber: "SAV-13-29",
			StudentName: "ROHIT PASWAN",
			MotherName: "ARTI DEVI",
			FathersName: "LALAN KUMAR PASWAN",
		},
		{
			SNO: "30",
			AdmissionNumber: "SAV-13-30",
			StudentName: "ABHINAV ANAL",
			MotherName: "BABITA KUMARI",
			FathersName: "BHANU PRATAP MANDAL",
		},
		{
			SNO: "31",
			AdmissionNumber: "SAV-13-32",
			StudentName: "SHIVAM KUMAR",
			MotherName: "KANTI KUMARI",
			FathersName: "YUGESH CHAUDHARY",
		},
		{
			SNO: "32",
			AdmissionNumber: "SAV-13-33",
			StudentName: "SUBHASH KUMAR",
			MotherName: "KIRAN KUMARI",
			FathersName: "SAKALDEO PRASAD",
		},
		{
			SNO: "33",
			AdmissionNumber: "SAV-13-34",
			StudentName: "GYANODAY KUMAR",
			MotherName: "JANKI DEVI",
			FathersName: "AKHILESH PRASAD",
		},
		{
			SNO: "34",
			AdmissionNumber: "SAV-13-35",
			StudentName: "HARSH ANAND",
			MotherName: "POONAM PRABHA",
			FathersName: "ANIL KUMAR",
		},
		{
			SNO: "35",
			AdmissionNumber: "SAV-13-36",
			StudentName: "PRASHANT BHUSAN",
			MotherName: "PREM LATA SINHA",
			FathersName: "ASHILESH KUMAR",
		},
		{
			SNO: "36",
			AdmissionNumber: "SAV-13-37",
			StudentName: "PIYUSH RAJ",
			MotherName: "SAVITA DEVI",
			FathersName: "NANDLALA RAM",
		},
		{
			SNO: "37",
			AdmissionNumber: "SAV-13-38",
			StudentName: "PARWEJ MUSHARRAF",
			MotherName: "NIKHAL AHMADI",
			FathersName: "ZAMEAL AKATAR",
		},
		{
			SNO: "38",
			AdmissionNumber: "SAV-13-39",
			StudentName: "SAKET KUMAR SUMAN",
			MotherName: "SUNILA DEVI",
			FathersName: "VIJAY KUMAR",
		},
		{
			SNO: "39",
			AdmissionNumber: "SAV-13-40",
			StudentName: "MANAS KUMAR",
			MotherName: "CHANDRAWTI DEVI",
			FathersName: "GANESH BAITHA",
		},
		{
			SNO: "40",
			AdmissionNumber: "SAV-13-41",
			StudentName: "VICKY KUMAR",
			MotherName: "PRAMILA DEVI",
			FathersName: "SURENDRA SINGH",
		},
		{
			SNO: "41",
			AdmissionNumber: "SAV-13-42",
			StudentName: "ANURODH RAJ",
			MotherName: "KUMARI USHA SINHA",
			FathersName: "AJAY KUMAR",
		},
		{
			SNO: "42",
			AdmissionNumber: "SAV-13-43",
			StudentName: "TANUJ KUMAR MANGLAM",
			MotherName: "NILAM DEVI",
			FathersName: "SUNIL KUMAR",
		},
		{
			SNO: "43",
			AdmissionNumber: "SAV-13-44",
			StudentName: "RAHUL RANJAN KUMAR",
			MotherName: "MUNNI DEVI",
			FathersName: "RAJU RANJAN KUMAR SINGH",
		},
		{
			SNO: "44",
			AdmissionNumber: "SAV-13-45",
			StudentName: "JAY KRISHNA KUMAR",
			MotherName: "RENU DEVI",
			FathersName: "SATISH KUMAR SINGH",
		},
		{
			SNO: "45",
			AdmissionNumber: "SAV-13-46",
			StudentName: "NAVIN KUMAR",
			MotherName: "USHA PANDAY",
			FathersName: "VINODANAND PANDAY",
		},
		{
			SNO: "46",
			AdmissionNumber: "SAV-13-47",
			StudentName: "RUDRA RANJAN",
			MotherName: "UPASANA RAJI",
			FathersName: "MANOJ KUMAR JAYSWAL",
		},
		{
			SNO: "47",
			AdmissionNumber: "SAV-13-48",
			StudentName: "RAJNISH KUMAR",
			MotherName: "PUNIA DEVI",
			FathersName: "RAJU KUMAR",
		},
		{
			SNO: "48",
			AdmissionNumber: "SAV-13-49",
			StudentName: "RAVI KUMAR BAITHA",
			MotherName: "CHINTA DEVI",
			FathersName: "NANDLAL BAITHA",
		},
		{
			SNO: "49",
			AdmissionNumber: "SAV-13-50",
			StudentName: "ROHIT RAJ",
			MotherName: "NIRMALA DEVI",
			FathersName: "RAJEEV KUMAR",
		},
		{
			SNO: "50",
			AdmissionNumber: "SAV-13-51",
			StudentName: "UJJWALKANT SINGH",
			MotherName: "POONAM DEVI",
			FathersName: "RAJKISHOR SINGH",
		},
		{
			SNO: "51",
			AdmissionNumber: "SAV-13-52",
			StudentName: "ANKIT KUMAR",
			MotherName: "NEELU KUMARI",
			FathersName: "AMOD KUMAR",
		},
		{
			SNO: "52",
			AdmissionNumber: "SAV-13-53",
			StudentName: "YASHWANT RAJ",
			MotherName: "REKHA DEVI",
			FathersName: "RANDHEER KUMAR SINGH",
		},
		{
			SNO: "53",
			AdmissionNumber: "SAV-13-54",
			StudentName: "SATYAM PASWAN",
			MotherName: "HEMANTI DEVI",
			FathersName: "DINESH KUMAR PASWAN",
		},
		{
			SNO: "54",
			AdmissionNumber: "SAV-13-55",
			StudentName: "PRINCE KUMAR",
			MotherName: "PUNITA DEVI",
			FathersName: "KAPIDHWAJ SINGH",
		},
		{
			SNO: "55",
			AdmissionNumber: "SAV-13-56",
			StudentName: "NVNIT KUMAR",
			MotherName: "SNENALATA DEVI",
			FathersName: "JYOTISH CHANDRA SAH",
		},
		{
			SNO: "56",
			AdmissionNumber: "SAV-13-57",
			StudentName: "SUNNY KUMAR",
			MotherName: "REENA DEVI",
			FathersName: "SUNIL HAZARA",
		},
		{
			SNO: "57",
			AdmissionNumber: "SAV-13-58",
			StudentName: "Niraj Kumar",
			MotherName: "Manju Kumari",
			FathersName: "Jagdeo Kumar",
		},

		{
			SNO: "58",
			AdmissionNumber: "SAV-13-61",
			StudentName: "SRISHTI RAJ",
			MotherName: "RADHIKA DEVI",
			FathersName: "JITENDRA RAY",
		},
		{
			SNO: "59",
			AdmissionNumber: "SAV-13-62",
			StudentName: "ANSHU KUMARI",
			MotherName: "LALITA DEVI",
			FathersName: "NAVIN KUMAR",
		},
		{
			SNO: "60",
			AdmissionNumber: "SAV-13-63",
			StudentName: "ANUPAMA KUMARI",
			MotherName: "KIRAN PANDEY",
			FathersName: "SUBODH PANDEY",
		},
		{
			SNO: "61",
			AdmissionNumber: "SAV-13-64",
			StudentName: "SONAM KUMARI",
			MotherName: "MALTI DEVI",
			FathersName: "SUMESHWAR SAH",
		},
		{
			SNO: "62",
			AdmissionNumber: "SAV-13-65",
			StudentName: "NEHA KUMARI",
			MotherName: "LAKSHMI DEVI",
			FathersName: "PREMLAL GOND",
		},
		{
			SNO: "63",
			AdmissionNumber: "SAV-13-66",
			StudentName: "SAPNA KUMARI",
			MotherName: "DEWNANTI KUMARI",
			FathersName: "PANKAJ KUMAR SINHA",
		},
		{
			SNO: "64",
			AdmissionNumber: "SAV-13-67",
			StudentName: "ANJALI KUMARI",
			MotherName: "GEETA DEVI",
			FathersName: "RANVIJAY SINGH",
		},
		{
			SNO: "65",
			AdmissionNumber: "SAV-13-68",
			StudentName: "TANU PRIYA",
			MotherName: "SHABNAM KUMARI",
			FathersName: "SANTOSH KUMAR",
		},
		{
			SNO: "66",
			AdmissionNumber: "SAV-13-69",
			StudentName: "ANJALI KUMARI",
			MotherName: "SUMAN SONI",
			FathersName: "SANTOSH SONI",
		},
		{
			SNO: "67",
			AdmissionNumber: "SAV-13-70",
			StudentName: "AKANKSHA KUMARI",
			MotherName: "ANITA KUMARI",
			FathersName: "ABHAY KUMAR",
		},
		{
			SNO: "68",
			AdmissionNumber: "SAV-13-71",
			StudentName: "SHIKHA KUMARI",
			MotherName: "INDU DEVI",
			FathersName: "MRITUNJAY KUMAR",
		},
		{
			SNO: "69",
			AdmissionNumber: "SAV-13-72",
			StudentName: "SHILPA KUMARI",
			MotherName: "KUMARI ARCHANA",
			FathersName: "SHIV KUMAR",
		},
		{
			SNO: "70",
			AdmissionNumber: "SAV-13-73",
			StudentName: "JANVI RAJ",
			MotherName: "SARITA DEVI",
			FathersName: "SUDHIR KUMAR",
		},
		{
			SNO: "71",
			AdmissionNumber: "SAV-13-74",
			StudentName: "BABLI BHARTI",
			MotherName: "SANGITA DEVI",
			FathersName: "CHANDRAMOULI PRASAD",
		},
		{
			SNO: "72",
			AdmissionNumber: "SAV-13-75",
			StudentName: "SALONI PRIYA",
			MotherName: "ANITA DEVI",
			FathersName: "SACHINDRA KUMAR",
		},
		{
			SNO: "73",
			AdmissionNumber: "SAV-13-76",
			StudentName: "SUJATA KUMARI",
			MotherName: "GEETA DEVI",
			FathersName: "AJAY KUMAR",
		},
		{
			SNO: "74",
			AdmissionNumber: "SAV-13-77",
			StudentName: "JYOTI KUMARI",
			MotherName: "CHANDRAVATI DEVI",
			FathersName: "SUNIL KUMAR",
		},
		{
			SNO: "75",
			AdmissionNumber: "SAV-13-78",
			StudentName: "ANU SHREE",
			MotherName: "SMT. SUNITA KUMARI",
			FathersName: "SRI PRABHU RAI",
		},
		{
			SNO: "76",
			AdmissionNumber: "SAV-13-79",
			StudentName: "ADITYA KUMARI",
			MotherName: "BHARTI DEVI",
			FathersName: "ANIL KUMAR",
		},
		{
			SNO: "77",
			AdmissionNumber: "SAV-13-80",
			StudentName: "PRATIBHA KUMARI",
			MotherName: "KIRAN DEVI",
			FathersName: "AMRENDRA KUMAR",
		},
		{
			SNO: "78",
			AdmissionNumber: "SAV-13-81",
			StudentName: "VIJETA RAJ",
			MotherName: "SUMAN KUMARI",
			FathersName: "VIJAY KUMAR PRASAD",
		},
		{
			SNO: "79",
			AdmissionNumber: "SAV-13-82",
			StudentName: "RAJSMITA",
			MotherName: "REEMA DEVI",
			FathersName: "RAJ KUMAR PODDAR",
		},
		{
			SNO: "80",
			AdmissionNumber: "SAV-13-83",
			StudentName: "RUPAM KUMARI",
			MotherName: "HEMANTI DEVI",
			FathersName: "RAM CHANDRA PRASAD",
		},
		{
			SNO: "81",
			AdmissionNumber: "SAV-13-84",
			StudentName: "SAROJA KUMARI",
			MotherName: "ASHA DEVI",
			FathersName: "JAY RAM PANDIT",
		},
		{
			SNO: "82",
			AdmissionNumber: "SAV-13-85",
			StudentName: "PRERANA RAJ",
			MotherName: "SANTARA KUMARI",
			FathersName: "LAL BAHADUR SINGH",
		},
		{
			SNO: "83",
			AdmissionNumber: "SAV-13-86",
			StudentName: "PRAGYA",
			MotherName: "BINITA KUMARI",
			FathersName: "PRAMOD KUMAR",
		},
		{
			SNO: "84",
			AdmissionNumber: "SAV-13-87",
			StudentName: "SONAL SINHA",
			MotherName: "PREBHA KUMARI",
			FathersName: "VIVEKANAND SINHG",
		},
		{
			SNO: "85",
			AdmissionNumber: "SAV-13-88",
			StudentName: "PRIYANKA KUMARI",
			MotherName: "JULI DEVI",
			FathersName: "LALAN KUMAR DAS",
		},
		{
			SNO: "86",
			AdmissionNumber: "SAV-13-89",
			StudentName: "HEMLATA KUMARI",
			MotherName: "MEENA DEVI",
			FathersName: "ARUN KR. MANDAL",
		},
		{
			SNO: "87",
			AdmissionNumber: "SAV-13-90",
			StudentName: "ANUPRIYA KUMARI",
			MotherName: "PUSHPA DEVI",
			FathersName: "RAVINDRA CHAUDHARY",
		},
		{
			SNO: "88",
			AdmissionNumber: "SAV-13-91",
			StudentName: "RASHI",
			MotherName: "LALTI DEVI",
			FathersName: "PRADEEP SAH",
		},
		{
			SNO: "89",
			AdmissionNumber: "SAV-13-92",
			StudentName: "SIMRAN KUAMARI",
			MotherName: "ANITA DEVI",
			FathersName: "BHOLA MANDAL",
		},
		{
			SNO: "90",
			AdmissionNumber: "SAV-13-93",
			StudentName: "PALLAVI PRIYA",
			MotherName: "BABITA DEVI",
			FathersName: "AJAY KUMAR",
		},
		{
			SNO: "91",
			AdmissionNumber: "SAV-13-94",
			StudentName: "ANJALI BHARTI",
			MotherName: "ANITA KUMARI SINHA",
			FathersName: "VINAY KR. SINHA",
		},
		{
			SNO: "92",
			AdmissionNumber: "SAV-13-95",
			StudentName: "CHANDANI KUMARI",
			MotherName: "SANYOGITA DEVI",
			FathersName: "HARERAM PRASAD",
		},
		{
			SNO: "93",
			AdmissionNumber: "SAV-13-96",
			StudentName: "SUHANI KUMARI",
			MotherName: "SUSHMA DEVI",
			FathersName: "RAMASHRAY PRASAD",
		},
		{
			SNO: "94",
			AdmissionNumber: "SAV-13-97",
			StudentName: "SALONI KUMARY",
			MotherName: "ANJANA",
			FathersName: "UPENDRA KUMAR",
		},
		{
			SNO: "95",
			AdmissionNumber: "SAV-13-98",
			StudentName: "SNEHA KUMARI",
			MotherName: "KUMARI NEEMA",
			FathersName: "RANJAN KUMAR JAISWAL",
		},
		{
			SNO: "96",
			AdmissionNumber: "SAV-13-99",
			StudentName: "SALONI KUMARI",
			MotherName: "SHAILWALA DEVI",
			FathersName: "ARUN KUMAR SINGH",
		},
		{
			SNO: "97",
			AdmissionNumber: "SAV-13-100",
			StudentName: "MANISHA KUMARI",
			MotherName: "TANKI DEVI",
			FathersName: "PRATAP MANDAL",
		},
		{
			SNO: "98",
			AdmissionNumber: "SAV-13-101",
			StudentName: "PRERNA RAJ",
			MotherName: "PINKI KUMARI",
			FathersName: "PRITAM KUMAR",
		},
		{
			SNO: "99",
			AdmissionNumber: "SAV-13-102",
			StudentName: "ANANYA ANAND",
			MotherName: "BABITA KUMARI",
			FathersName: "RAJDEEP ANAND",
		},
		{
			SNO: "100",
			AdmissionNumber: "SAV-13-103",
			StudentName: "SNEHA KUMARI",
			MotherName: "PARTIMA KUMARI",
			FathersName: "MUKESH KUMAR",
		},
		{
			SNO: "101",
			AdmissionNumber: "SAV-13-104",
			StudentName: "SUPRIYA KUMARI",
			MotherName: "REENA DEVI",
			FathersName: "RAKESH KUMAR",
		},
		{
			SNO: "102",
			AdmissionNumber: "SAV-13-105",
			StudentName: "POONAM KUMARI",
			MotherName: "VIDYA KUMARI",
			FathersName: "SURAJ PRASAD",
		},
		{
			SNO: "103",
			AdmissionNumber: "SAV-13-106",
			StudentName: "KHUSHBU KUMARI",
			MotherName: "NIRMAL KUMARI",
			FathersName: "PRABHU NARAYAN SAH",
		},
		{
			SNO: "104",
			AdmissionNumber: "SAV-13-107",
			StudentName: "TANU PRIYA",
			MotherName: "RANJU SHARMA",
			FathersName: "GOPAL SHARAN SHAMA",
		},
	],
};
