/** @format */

export const initstate11 = {
	profiles: [
		{
			SNO: "1",
			AdmissionNumber: "SAV-11-01",
			StudentName: "ROHIT KUMAR VISHWAS",
			FathersName: "PRABHAT KUMAR VISHWAS",
		},
		{
			SNO: "2",
			AdmissionNumber: "SAV-11-02",
			StudentName: "SUBHASH KUMAR",
			FathersName: "KAMLESH PASWAN",
		},
		{
			SNO: "3",
			AdmissionNumber: "SAV-11-04",
			StudentName: "ABHINAV SHARMA",
			FathersName: "AVINASH CHANDRA SHARMA",
		},
		{
			SNO: "4",
			AdmissionNumber: "SAV-11-05",
			StudentName: "ABHISHEK ANAND",
			FathersName: "GULAB PRASAD YADAV",
		},
		{
			SNO: "5",
			AdmissionNumber: "SAV-11-06",
			StudentName: "CHHOTU KUMAR",
			FathersName: "SURENDRA MOHAN SAH",
		},
		{
			SNO: "6",
			AdmissionNumber: "SAV-11-07",
			StudentName: "PRIYANSHU KUMAR",
			FathersName: "ABHAY KUMAR MANDAL",
		},
		{
			SNO: "7",
			AdmissionNumber: "SAV-11-08",
			StudentName: "SIDHARTH SHEKHAR",
			FathersName: "DINESH PANDIT",
		},
		{
			SNO: "8",
			AdmissionNumber: "SAV-11-09",
			StudentName: "SUMIT KUMAR",
			FathersName: "ADITYA KUMAR",
		},
		{
			SNO: "9",
			AdmissionNumber: "SAV-11-10",
			StudentName: "NAMAN KUMAR",
			FathersName: "SHIV KUMAR AGRAWAL",
		},
		{
			SNO: "10",
			AdmissionNumber: "SAV-11-11",
			StudentName: "RITU RAJ",
			FathersName: "BIJAY KUMAR",
		},
		{
			SNO: "11",
			AdmissionNumber: "SAV-11-12",
			StudentName: "RAJA BANSHI",
			FathersName: "BIPIN KESHRI",
		},
		{
			SNO: "12",
			AdmissionNumber: "SAV-11-13",
			StudentName: "SURAJ KUMAR",
			FathersName: "PRBHU KUMAR SINGH",
		},
		{
			SNO: "13",
			AdmissionNumber: "SAV-11-14",
			StudentName: "ABHISHEK KUMAR",
			FathersName: "SANJAY SINGH",
		},
		{
			SNO: "14",
			AdmissionNumber: "SAV-11-15",
			StudentName: "SUNIL KUMAR",
			FathersName: "MOTILAL PATEL",
		},
		{
			SNO: "15",
			AdmissionNumber: "SAV-11-16",
			StudentName: "PRITHWI RAJ",
			FathersName: "BAIRISTRA THAKUR",
		},
		{
			SNO: "16",
			AdmissionNumber: "SAV-11-17",
			StudentName: "VICKY KUMAR",
			FathersName: "YOGENDRA CHAUDHARY",
		},
		{
			SNO: "17",
			AdmissionNumber: "SAV-11-18",
			StudentName: "MADHUKAR",
			FathersName: "DIWAKAR KUMAR",
		},
		{
			SNO: "18",
			AdmissionNumber: "SAV-11-19",
			StudentName: "ANURAG KUMAR",
			FathersName: "DEVENDRA KUMAR RAY",
		},
		{
			SNO: "19",
			AdmissionNumber: "SAV-11-21",
			StudentName: "SUMIT BHARDWAJ",
			FathersName: "RAVENESHWAR ASHUTOSH",
		},
		{
			SNO: "20",
			AdmissionNumber: "SAV-11-22",
			StudentName: "RAHUL KUMAR",
			FathersName: "NAND KUMAR PRASAD",
		},
		{
			SNO: "21",
			AdmissionNumber: "SAV-11-23",
			StudentName: "IRSHAD AHMAD",
			FathersName: "WAKIL AHMAD",
		},
		{
			SNO: "22",
			AdmissionNumber: "SAV-11-24",
			StudentName: "SUMIT SHEKHAR",
			FathersName: "SHIV SHANKAR PRASAD",
		},
		{
			SNO: "23",
			AdmissionNumber: "SAV-11-25",
			StudentName: "ADARSH ANAND",
			FathersName: "GIRISH KUMAR SHARMA",
		},
		{
			SNO: "24",
			AdmissionNumber: "SAV-11-26",
			StudentName: "PAWAN KUMAR",
			FathersName: "BIHARI JEE BHAGAT",
		},
		{
			SNO: "25",
			AdmissionNumber: "SAV-11-27",
			StudentName: "PRINCE RAJ",
			FathersName: "RAMNARESH CHAUDHARY",
		},
		{
			SNO: "26",
			AdmissionNumber: "SAV-11-28",
			StudentName: "ASHUTOSH KUMAR",
			FathersName: "ARVIND KUMAR",
		},
		{
			SNO: "27",
			AdmissionNumber: "SAV-11-29",
			StudentName: "SATYAM KUMAR",
			FathersName: "YUGAL KISHORE",
		},
		{
			SNO: "28",
			AdmissionNumber: "SAV-11-30",
			StudentName: "TANMAY",
			FathersName: "RAM NATH ROY",
		},
		{
			SNO: "29",
			AdmissionNumber: "SAV-11-31",
			StudentName: "CHANDRALOK KUMAR",
			FathersName: "SATYENDRA KUMAR",
		},
		{
			SNO: "30",
			AdmissionNumber: "SAV-11-32",
			StudentName: "MD. PARWEZ",
			FathersName: "MD. AYUB",
		},
		{
			SNO: "31",
			AdmissionNumber: "SAV-11-34",
			StudentName: "JEEVAN PRAKASH",
			FathersName: "SURAJ RAM",
		},
		{
			SNO: "32",
			AdmissionNumber: "SAV-11-35",
			StudentName: "ABHINANDAN KUMAR",
			FathersName: "SHANKAR PRASAD",
		},
		{
			SNO: "33",
			AdmissionNumber: "SAV-11-36",
			StudentName: "SUMIT KUMAR",
			FathersName: "RAMAYAN SINGH",
		},
		{
			SNO: "34",
			AdmissionNumber: "SAV-11-37",
			StudentName: "SUMIT KUMAR",
			FathersName: "DEONANDAN CHAUDHARY",
		},
		{
			SNO: "35",
			AdmissionNumber: "SAV-11-38",
			StudentName: "PIYUSH KUMAR",
			FathersName: "DHIRENDRA KUMAR",
		},
		{
			SNO: "36",
			AdmissionNumber: "SAV-11-39",
			StudentName: "SHASHIKANT RANJAN",
			FathersName: "DHANANJAY PRASAD",
		},
		{
			SNO: "37",
			AdmissionNumber: "SAV-11-40",
			StudentName: "AYUSH KUMAR NIRAJ",
			FathersName: "DILIP KUMAR",
		},
		{
			SNO: "38",
			AdmissionNumber: "SAV-11-41",
			StudentName: "NAVLESH RAJ",
			FathersName: "NITISH KUMAR",
		},
		{
			SNO: "39",
			AdmissionNumber: "SAV-11-42",
			StudentName: "RAHUL KUMAR",
			FathersName: "CHANDESHWAR PASWAN",
		},
		{
			SNO: "40",
			AdmissionNumber: "SAV-11-43",
			StudentName: "ROHIT KUMAR CHAUHAN",
			FathersName: "MOHAN MAHATO",
		},
		{
			SNO: "41",
			AdmissionNumber: "SAV-11-44",
			StudentName: "SHAMSUZ ZAMA",
			FathersName: "ABDUS SAMAD",
		},
		{
			SNO: "42",
			AdmissionNumber: "SAV-11-45",
			StudentName: "RAMAN KUMAR",
			FathersName: "AJAY KUMAR ROY",
		},
		{
			SNO: "43",
			AdmissionNumber: "SAV-11-46",
			StudentName: "PAWAN KUMAR",
			FathersName: "SRI BHAGWAN SINGH",
		},
		{
			SNO: "44",
			AdmissionNumber: "SAV-11-47",
			StudentName: "MAYANK SHEKHAR",
			FathersName: "DIWAKAR MANDAL TEACHER",
		},
		{
			SNO: "45",
			AdmissionNumber: "SAV-11-48",
			StudentName: "AKSHAT KUMAR",
			FathersName: "MANOJ KUMAR",
		},
		{
			SNO: "46",
			AdmissionNumber: "SAV-11-49",
			StudentName: "SANJAY KAZI",
			FathersName: "HARINARAYAN KAZI",
		},
		{
			SNO: "47",
			AdmissionNumber: "SAV-11-50",
			StudentName: "ROHIT KUMAR",
			FathersName: "SOMAR SINGH",
		},
		{
			SNO: "48",
			AdmissionNumber: "SAV-11-51",
			StudentName: "ATUL ANAND",
			FathersName: "PANKAJ KUMAR SINGH",
		},
		{
			SNO: "49",
			AdmissionNumber: "SAV-11-52",
			StudentName: "RADHAMOHAN",
			FathersName: "DINESH KUMAR",
		},
		{
			SNO: "50",
			AdmissionNumber: "SAV-11-53",
			StudentName: "SANJEEV KUMAR",
			FathersName: "AJAY KUMAR",
		},
		{
			SNO: "51",
			AdmissionNumber: "SAV-11-54",
			StudentName: "PRINCE RAJ",
			FathersName: "RAJ KUMAR SINGH",
		},
		{
			SNO: "52",
			AdmissionNumber: "SAV-11-56",
			StudentName: "SUMIT KUMAR",
			FathersName: "SHAILESH PRASAD",
		},
		{
			SNO: "53",
			AdmissionNumber: "SAV-11-57",
			StudentName: "ALOK RAJ",
			FathersName: "KAMLESH KUMAR",
		},
		{
			SNO: "54",
			AdmissionNumber: "SAV-11-58",
			StudentName: "ROHIT KUMAR",
			FathersName: "KARU SAW",
		},
		{
			SNO: "55",
			AdmissionNumber: "SAV-11-59",
			StudentName: "ABHISHEK RAJ",
			FathersName: "UPENDRA PRASAD SINGH",
		},
		{
			SNO: "56",
			AdmissionNumber: "SAV-11-60",
			StudentName: "ANAND VARDHAN SONU",
			FathersName: "PRAMOD PRASAD SINGH",
		},
		{
			SNO: "57",
			AdmissionNumber: "SAV-11-127",
			StudentName: "RAJAT PRAKASH",
			FathersName: "LALAN KUMAR LALAN",
		},
		{
			SNO: "58",
			AdmissionNumber: "SAV-11-128",
			StudentName: "PRIYANSHU KUMAR",
			FathersName: "SUNIL BAITHA",
		},
		{
			SNO: "59",
			AdmissionNumber: "SAV-11-61",
			StudentName: "KOMAL KUMARI",
			FathersName: "KAMLESH KUMAR",
		},
		{
			SNO: "60",
			AdmissionNumber: "SAV-11-62",
			StudentName: "VERSHA KUMARI",
			FathersName: "KAPILDEO SAH",
		},
		{
			SNO: "61",
			AdmissionNumber: "SAV-11-63",
			StudentName: "KUMARI ASTHA",
			FathersName: "ASHOK KUMAR MANDAL",
		},
		{
			SNO: "62",
			AdmissionNumber: "SAV-11-64",
			StudentName: "PUJA KUMARI",
			FathersName: "NIRANJAN SINGH",
		},
		{
			SNO: "63",
			AdmissionNumber: "SAV-11-65",
			StudentName: "MEGHA KIRAN",
			FathersName: "MAHESH KUMAR CHOUDHARY",
		},
		{
			SNO: "64",
			AdmissionNumber: "SAV-11-66",
			StudentName: "SANYA ROUSHAN",
			FathersName: "SANJAY PRASAD",
		},
		{
			SNO: "65",
			AdmissionNumber: "SAV-11-67",
			StudentName: "RAKHI KUMARI",
			FathersName: "JAYCHAND DAS",
		},
		{
			SNO: "66",
			AdmissionNumber: "SAV-11-68",
			StudentName: "SHAMIKSHA KUMARI",
			FathersName: "AJIT KUMAR",
		},
		{
			SNO: "67",
			AdmissionNumber: "SAV-11-69",
			StudentName: "SUMAN KUMARI",
			FathersName: "JYOTISH PASWAN",
		},
		{
			SNO: "68",
			AdmissionNumber: "SAV-11-70",
			StudentName: "DIVYA JYOTI",
			FathersName: "ANIL MANDAL",
		},
		{
			SNO: "69",
			AdmissionNumber: "SAV-11-71",
			StudentName: "ANANYA",
			FathersName: "DINESH KUMAR",
		},
		{
			SNO: "70",
			AdmissionNumber: "SAV-11-72",
			StudentName: "JYOTSNA",
			FathersName: "PAWAN KUMAR",
		},
		{
			SNO: "71",
			AdmissionNumber: "SAV-11-73",
			StudentName: "PREETY KUMARI",
			FathersName: "KUMAR RAJIV RANJAN",
		},
		{
			SNO: "72",
			AdmissionNumber: "SAV-11-74",
			StudentName: "RAJDIVYA",
			FathersName: "INDRAMOHAN PODDAR",
		},
		{
			SNO: "73",
			AdmissionNumber: "SAV-11-75",
			StudentName: "SHAUKTIKA SHASWAT",
			FathersName: "BINOD KUMAR ROY",
		},
		{
			SNO: "74",
			AdmissionNumber: "SAV-11-76",
			StudentName: "AKRITI KUMARI",
			FathersName: "SHAMBHU KUMAR GUPTA",
		},
		{
			SNO: "75",
			AdmissionNumber: "SAV-11-77",
			StudentName: "SADIYA SADAF",
			FathersName: "ABDUL QAIYUM",
		},
		{
			SNO: "76",
			AdmissionNumber: "SAV-11-78",
			StudentName: "AMRITA KUMARI",
			FathersName: "MUNNA KUMAR",
		},
		{
			SNO: "77",
			AdmissionNumber: "SAV-11-79",
			StudentName: "SHILPA SHREYA",
			FathersName: "ASHOK KUMAR MANDAL",
		},
		{
			SNO: "78",
			AdmissionNumber: "SAV-11-80",
			StudentName: "JELSY SINGH",
			FathersName: "SANJAY KUMAR SINGH",
		},
		{
			SNO: "79",
			AdmissionNumber: "SAV-11-81",
			StudentName: "RITU RANI",
			FathersName: "RAM LOCHAN SHARAN",
		},
		{
			SNO: "80",
			AdmissionNumber: "SAV-11-82",
			StudentName: "ADITI SARTHAK",
			FathersName: "PRADEEP KUMAR",
		},
		{
			SNO: "81",
			AdmissionNumber: "SAV-11-83",
			StudentName: "PRIYANKA KUMARI",
			FathersName: "NARENDRA NARAYAN SINHA",
		},
		{
			SNO: "82",
			AdmissionNumber: "SAV-11-84",
			StudentName: "ANU KUMARI",
			FathersName: "BIHARI SAH",
		},
		{
			SNO: "83",
			AdmissionNumber: "SAV-11-85",
			StudentName: "SHUBHAM KUMARI",
			FathersName: "DHARMENDRA PRASAD SINGH",
		},
		{
			SNO: "84",
			AdmissionNumber: "SAV-11-86",
			StudentName: "SIMRAN KUMARI",
			FathersName: "SUNIL KUMAR SINGH",
		},
		{
			SNO: "85",
			AdmissionNumber: "SAV-11-87",
			StudentName: "VIVEK PRABHA",
			FathersName: "JAIRAM DAS",
		},
		{
			SNO: "86",
			AdmissionNumber: "SAV-11-88",
			StudentName: "SUPRIYA PATEL",
			FathersName: "SUMAN PATEL",
		},
		{
			SNO: "87",
			AdmissionNumber: "SAV-11-89",
			StudentName: "ABHA KUMARI",
			FathersName: "JAI PRAKASH PRASAD",
		},
		{
			SNO: "88",
			AdmissionNumber: "SAV-11-90",
			StudentName: "POOJA KUMARI",
			FathersName: "MANJEET KUMAR VERMA",
		},
		{
			SNO: "89",
			AdmissionNumber: "SAV-11-91",
			StudentName: "AMRITA PATEL",
			FathersName: "BIJENDRA KUMAR",
		},
		{
			SNO: "90",
			AdmissionNumber: "SAV-11-92",
			StudentName: "ANSHU PRIYA",
			FathersName: "RAMDEO SINGH",
		},
		{
			SNO: "91",
			AdmissionNumber: "SAV-11-94",
			StudentName: "NISHA KUMARI",
			FathersName: "SHASHI PRASAD",
		},
		{
			SNO: "92",
			AdmissionNumber: "SAV-11-95",
			StudentName: "SALONI PRIYA",
			FathersName: "SANAT KUMAR",
		},
		{
			SNO: "93",
			AdmissionNumber: "SAV-11-96",
			StudentName: "KUMARI MANSI",
			FathersName: "KRISHNA SINGH",
		},
		{
			SNO: "94",
			AdmissionNumber: "SAV-11-97",
			StudentName: "ANSHIKA RAJ",
			FathersName: "DHANANJAY SHARMA",
		},
		{
			SNO: "95",
			AdmissionNumber: "SAV-11-98",
			StudentName: "VINITA KUMARI",
			FathersName: "VIJAY KUMAR RAMAN",
		},
		{
			SNO: "96",
			AdmissionNumber: "SAV-11-99",
			StudentName: "REEMA KUMARI",
			FathersName: "MUKESH SINGH",
		},
		{
			SNO: "97",
			AdmissionNumber: "SAV-11-100",
			StudentName: "SONALI PRIYA",
			FathersName: "MAHESH BABU CHAUDHARY",
		},
		{
			SNO: "98",
			AdmissionNumber: "SAV-11-101",
			StudentName: "SUPRIYA KUMARI",
			FathersName: "SANJAY SINGH",
		},
		{
			SNO: "99",
			AdmissionNumber: "SAV-11-102",
			StudentName: "RAGINI KUMARI",
			FathersName: "YOGENDRA PRASAD YADAV",
		},
		{
			SNO: "100",
			AdmissionNumber: "SAV-11-103",
			StudentName: "SWEETI KUMARI",
			FathersName: "RAKESH KUMAR THAKUR",
		},
		{
			SNO: "101",
			AdmissionNumber: "SAV-11-104",
			StudentName: "AARYA KUMARI",
			FathersName: "SATYENDRA SINGH",
		},
		{
			SNO: "102",
			AdmissionNumber: "SAV-11-105",
			StudentName: "MINI JOSI",
			FathersName: "SUBHASH SINGH",
		},
		{
			SNO: "103",
			AdmissionNumber: "SAV-11-107",
			StudentName: "YASHASWI RAJ",
			FathersName: "LALAN KUMAR",
		},
		{
			SNO: "104",
			AdmissionNumber: "SAV-11-108",
			StudentName: "PUJA KUMARI",
			FathersName: "NAVIN KUMAR",
		},
		{
			SNO: "105",
			AdmissionNumber: "SAV-11-109",
			StudentName: "PUJA KUMARI",
			FathersName: "SARVESH KUMAR",
		},
		{
			SNO: "106",
			AdmissionNumber: "SAV-11-110",
			StudentName: "MONAM KUMARI",
			FathersName: "NAGESHWAR PRASAD YADAV",
		},
		{
			SNO: "107",
			AdmissionNumber: "SAV-11-111",
			StudentName: "RIYA RAJ",
			FathersName: "BALIRAM PRASAD",
		},
		{
			SNO: "108",
			AdmissionNumber: "SAV-11-112",
			StudentName: "BABITA KUMARI",
			FathersName: "NAND KISHOR RAI",
		},
		{
			SNO: "109",
			AdmissionNumber: "SAV-11-113",
			StudentName: "SANTWANA KUMARI",
			FathersName: "RAJNISH KUMAR SINGH",
		},
		{
			SNO: "110",
			AdmissionNumber: "SAV-11-114",
			StudentName: "KHUSHBOO KUMARI",
			FathersName: "OM PRAKASH AGRAWAL",
		},
		{
			SNO: "111",
			AdmissionNumber: "SAV-11-115",
			StudentName: "KUSUM KUMARI",
			FathersName: "BHOLA PRASAD",
		},
		{
			SNO: "112",
			AdmissionNumber: "SAV-11-116",
			StudentName: "SUPRITY KUMARI",
			FathersName: "ANJANI KUMAR SINGH",
		},
		{
			SNO: "113",
			AdmissionNumber: "SAV-11-117",
			StudentName: "RUPAM RATAN",
			FathersName: "RATAN KUMAR",
		},
		{
			SNO: "114",
			AdmissionNumber: "SAV-11-118",
			StudentName: "JYOTI PRIYA",
			FathersName: "MANOJ KUMAR",
		},
		{
			SNO: "115",
			AdmissionNumber: "SAV-11-119",
			StudentName: "SHUBHANGI SREYA",
			FathersName: "DHARAM NATH PRASAD",
		},
		{
			SNO: "116",
			AdmissionNumber: "SAV-11-121",
			StudentName: "VINDHYA WASHINI",
			FathersName: "SANJAY PASWAN",
		},
		{
			SNO: "117",
			AdmissionNumber: "SAV-11-122",
			StudentName: "DIVYA SHIKHA",
			FathersName: "BIHARI LAL CHAUDHARY",
		},
		{
			SNO: "118",
			AdmissionNumber: "SAV-11-123",
			StudentName: "KHUSHI KUMARI",
			FathersName: "JYOTI PASWAN",
		},
		{
			SNO: "119",
			AdmissionNumber: "SAV-11-124",
			StudentName: "PRAGYA KUMARI",
			FathersName: "VIRENDRA KUMAR",
		},
		{
			SNO: "120",
			AdmissionNumber: "SAV-11-125",
			StudentName: "ANAMIKA KUMARI",
			FathersName: "RAM PRAKASH SINGH",
		},
		{
			SNO: "121",
			AdmissionNumber: "SAV-11-126",
			StudentName: "BHAWANI KUMARI",
			FathersName: "RAM BAHADUR SAHNI",
		},
	],
};
